version: "3.7"
services:
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_DB: mainzelliste-sel
      POSTGRES_USER: mainzelliste-sel
      POSTGRES_PASSWORD: ${MAINZELLISTE_DB_PASSWORD:-pleaseChangeMe}
    volumes:
      - postgresLogs:/var/log/postgresql
      - postgresData:/var/lib/postgresql/data
    depends_on:
      - secureepilinker
    networks:
      - intranet
     
  mainzelliste:
    image:  docker.verbis.dkfz.de/cord/mainzelliste:1.7.0-RC1-SEL15
    environment:
      ML_DB_HOST: postgres
      ML_DB_PORT: 5432
      ML_DB_USER: mainzelliste-sel
      ML_DB_NAME: mainzelliste-sel
      ML_DB_PASS: ${MAINZELLISTE_DB_PASSWORD:-pleaseChangeMe}
      LOCAL_ID: ${SITE:-anjou}
      LOCAL_SEL_URL: http://secureepilinker:8161
      LOCAL_CALLBACK_LINK_URL: http://mainzelliste:8080/Communicator/linkCallback
      LOCAL_CALLBACK_MATCH_URL: http://mainzelliste:8080/Communicator/matchCallback/${REMOTE_SITE:-bapu}
      LOCAL_DATA_SERVICE_URL: http://mainzelliste:8080/Communicator/getAllRecords
      LOCAL_AUTHENTICATION_TYPE: apiKey
      LOCAL_API_KEY: ${LOCAL_API_KEY:-thisApikeyIsNotSecure}
      SERVER_0_REMOTEID: ${REMOTE_SITE:-bapu}
      SERVER_0_IDTYPE: link-${SITE:-anjou}-${REMOTE_SITE:-bapu}
      SERVER_0_REMOTE_SEL_URL: http://${REMOTE_TUNNEL}:8161
      SERVER_0_APIKEY: ${REMOTE_API_KEY:-thisApikeyIsNotSecure}
      ### Linkage Service not used for matching
      SERVER_0_LINKAGE_SERVICE_BASE_URL: http://192.168.2.120:5000
      SERVER_0_LINKAGE_SERVICE_AUTH_TYPE: apiKey
      SERVER_0_LINKAGE_SERVICE_SHARED_KEY: bcd234
      LOG_MODE: stdout #stdout=stdout everything else =logging in mainzelliste.log
      LOG_LEVEL: DEBUG
    volumes:
      - mainzellisteLogs:/usr/local/tomcat/logs/
      - ./config/mainzelliste.conf.docker:/etc/mainzelliste/mainzelliste.conf.docker
      - ./config/sel.conf.docker:/etc/mainzelliste/sel.conf.docker
    depends_on:
      - postgres
      - secureepilinker
    networks:
      - intranet
  secureepilinker:
    ports:
      - "1337-1344"
      - "8161"
    image: docker.verbis.dkfz.de/cord/sel:v1.0.1-ubuntu	
    volumes:
      - "./config/epilinker.serverconf.json:/data/serverconf.json"
    command: '-vv'
    environment:
      LOG_LEVEL: DEBUG	
    networks:
      - intranet
      - frontend

networks:
  ### containers only in this network will not be able to access addresses outside this directory
  intranet:
    internal: true
  frontend:
    driver: bridge
volumes:
  mainzellisteLogs:
  postgresData:
  postgresLogs:
